/* AQUI TODOS LOS DROP DE LAS TABLAS EN ORDEN */
/* !!! OJO !!! PREGUNTAR A PROF QUE QUIERE HACER CON ESTO


   OJO ESTO NO ES ASÍ, HAY QUE QUITAR LOS CASCADE Y HACERLO BIEN

   */

DROP TABLE ACCION CASCADE ;

DROP TABLE CARA_TIPO CASCADE ;

DROP TABLE CARACTERISTICA CASCADE ;

DROP TABLE CARGO CASCADE ;

DROP TABLE CHEQUE CASCADE ;

DROP TABLE CLIENTE CASCADE ;

DROP TABLE COMPANIA CASCADE;

DROP TABLE CREDITO CASCADE ;

DROP TABLE DEBITO CASCADE ;

DROP TABLE EMPLEADO CASCADE ;

DROP TABLE EQUIPO CASCADE ;

DROP TABLE ESTADO CASCADE ;

DROP TABLE ETAPA CASCADE ;

DROP TABLE ETAPA_CONFIGURACION CASCADE ;

DROP TABLE FACTURA_COMPRA CASCADE ;

DROP TABLE FACTURA_VENTA CASCADE ;

DROP TABLE FASE CASCADE ;

DROP TABLE FASE_CARG CASCADE ;

DROP TABLE FASE_CONFIGURACION  CASCADE ;

DROP TABLE FASE_EMPL CASCADE ;

DROP TABLE FASE_EQUI CASCADE ;

DROP TABLE FASE_MAQU CASCADE ;

DROP TABLE GASTO_ADICIONAL CASCADE ;

DROP TABLE HORARIO CASCADE ;

DROP TABLE INVENTARIO CASCADE ;

DROP TABLE JORNADA CASCADE ;

DROP TABLE LUGAR CASCADE ;

DROP TABLE MAQUINARIA CASCADE ;

DROP TABLE MINE_MINE CASCADE ;

DROP TABLE MINE_YACI CASCADE ;

DROP TABLE MINERAL CASCADE ;

DROP TABLE PEDI_ESTA CASCADE ;

DROP TABLE PEDI_PROD CASCADE ;

DROP TABLE PEDI_TIPO CASCADE ;

DROP TABLE PEDIDO  CASCADE ;

DROP TABLE PROD_COMP CASCADE ;

DROP TABLE PROD_SOLI CASCADE ;

DROP TABLE PRODUCTO CASCADE ;

DROP TABLE PROYECTO CASCADE ;

DROP TABLE ROL CASCADE ;

DROP TABLE ROL_ACCI CASCADE ;

DROP TABLE SECT_MINE CASCADE ;

DROP TABLE SECTOR_USO CASCADE ;

DROP TABLE SOLICITUD CASCADE ;

DROP TABLE TIPO_YACIMIENTO cascade ;

DROP TABLE TRANSFERENCIA CASCADE ;

DROP TABLE UNIDAD  CASCADE ;

DROP TABLE USUARIO CASCADE ;

DROP TABLE YACIMIENTO  CASCADE ;

DROP TABLE YACIMIENTO_CONFIGURACION CASCADE ;